### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Davidyao99** [dichotomies/NeuralDiff#5]
I have followed the instructions and all the data and pre-trained models have been downloaded accordingly. However, I am receiving the above error when running the evaluation script. Any idea why this is happening? I have attached a screenshot of the error below.

![image](https://user-images.githubusercontent.com/52120948/201490344-af3bebb4-dbae-4e91-8ffd-39f898c0e27e.png)

I suspect that it might be to CUDA out-of-memory issues. I am using an NVIDIA GeForce GTX 1650 Ti with Max-Q. Is there anything I can do to get around this?

**Comment by dichotomies** [comment]
Hi David, this usually happens when a tensor element is accessed out of its bounds. In this implementation the error can occur if you modify `N_vocab` or keep it at 1000 while you use more frames with a custom dataset. Can you doublecheck that you have not modified the code at all (except for paths, if necessary)?

**Comment by dichotomies** [comment]
Alternatively, this could be indeed to OOM, especially since your GPU has only 4GB if I'm not mistaken. In this case I would recommend adjusting the argument "--chunk". This reduces the memory footprint by splitting the rays into chunks during the rendering. Note that this will slow down the rendering as well.

**Comment by mickaelbressieux** [comment]
I had the same problem and it turned out that it was the size on the images (~300kB). I modified line 38 of colmap_converter/\_\_main\_\_.py to take into account the argument _scale_ as such:
`meta = calc_meta(colmap, image_downscale=args.scale, split_nth=args.split_nth)`
The size of my images become similar to the ones of the data/EPIC-Diff (~80kB)

This solved my memory problem that even multiplying or dividing _chunk_ and _batch\_size_ couldn't solve. 

Note that the training does not go through if the colmap_converter preprocessing is done with the default argument  split_nth=0

Hope that helps!
